AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Takes Month and Day, and returns Zodiac Sign'
Resources:
  Zodiac:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: 'Takes Month and Day, and returns Zodiac Sign'
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::481708550652:role/service-role/Zodiac'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /
            Method: POST
        Api3:
          Type: Api
          Properties:
            Path: /Zodiac
            Method: ANY
